#############################################################################
# Makefile for building: XaTek
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  XaTek.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile XaTek.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = XaTek1.0.0
DISTDIR = /home/david/Qt/Projects/XaTek/.tmp/XaTek1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -lQt5QuickWidgets -lQt5QuickControls2 -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		connectivityform.cpp \
		datetimeform.cpp \
		displayforms.cpp \
		homescreen.cpp \
		insertclotchip.cpp \
		openscanclotchip.cpp \
		passcodeunlock.cpp \
		preparepatient.cpp \
		qualityassuranceform.cpp \
		serviceform.cpp \
		setadminpasscode.cpp \
		setpatientid.cpp \
		settingoptionsform.cpp \
		setuserid.cpp \
		setuserpasscode.cpp \
		verifyclotchip.cpp \
		viewtestresultsform.cpp \
		selectnetwork.cpp \
		bluetoothpairing.cpp \
		timelastdose.cpp \
		collectsample.cpp \
		preheatclotchip.cpp \
		testinprogress.cpp \
		keyboard.cpp \
		testresultdetails.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_connectivityform.cpp \
		moc_datetimeform.cpp \
		moc_displayforms.cpp \
		moc_homescreen.cpp \
		moc_insertclotchip.cpp \
		moc_openscanclotchip.cpp \
		moc_passcodeunlock.cpp \
		moc_preparepatient.cpp \
		moc_qualityassuranceform.cpp \
		moc_serviceform.cpp \
		moc_setadminpasscode.cpp \
		moc_setpatientid.cpp \
		moc_settingoptionsform.cpp \
		moc_setuserid.cpp \
		moc_setuserpasscode.cpp \
		moc_verifyclotchip.cpp \
		moc_viewtestresultsform.cpp \
		moc_selectnetwork.cpp \
		moc_bluetoothpairing.cpp \
		moc_timelastdose.cpp \
		moc_collectsample.cpp \
		moc_preheatclotchip.cpp \
		moc_testinprogress.cpp \
		moc_keyboard.cpp \
		moc_testresultdetails.cpp
OBJECTS       = main.o \
		mainwindow.o \
		connectivityform.o \
		datetimeform.o \
		displayforms.o \
		homescreen.o \
		insertclotchip.o \
		openscanclotchip.o \
		passcodeunlock.o \
		preparepatient.o \
		qualityassuranceform.o \
		serviceform.o \
		setadminpasscode.o \
		setpatientid.o \
		settingoptionsform.o \
		setuserid.o \
		setuserpasscode.o \
		verifyclotchip.o \
		viewtestresultsform.o \
		selectnetwork.o \
		bluetoothpairing.o \
		timelastdose.o \
		collectsample.o \
		preheatclotchip.o \
		testinprogress.o \
		keyboard.o \
		testresultdetails.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_connectivityform.o \
		moc_datetimeform.o \
		moc_displayforms.o \
		moc_homescreen.o \
		moc_insertclotchip.o \
		moc_openscanclotchip.o \
		moc_passcodeunlock.o \
		moc_preparepatient.o \
		moc_qualityassuranceform.o \
		moc_serviceform.o \
		moc_setadminpasscode.o \
		moc_setpatientid.o \
		moc_settingoptionsform.o \
		moc_setuserid.o \
		moc_setuserpasscode.o \
		moc_verifyclotchip.o \
		moc_viewtestresultsform.o \
		moc_selectnetwork.o \
		moc_bluetoothpairing.o \
		moc_timelastdose.o \
		moc_collectsample.o \
		moc_preheatclotchip.o \
		moc_testinprogress.o \
		moc_keyboard.o \
		moc_testresultdetails.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		XaTek.pro mainwindow.h \
		connectivityform.h \
		datetimeform.h \
		displayforms.h \
		homescreen.h \
		insertclotchip.h \
		openscanclotchip.h \
		passcodeunlock.h \
		preparepatient.h \
		qualityassuranceform.h \
		serviceform.h \
		setadminpasscode.h \
		setpatientid.h \
		settingoptionsform.h \
		setuserid.h \
		setuserpasscode.h \
		verifyclotchip.h \
		viewtestresultsform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		timelastdose.h \
		collectsample.h \
		preheatclotchip.h \
		testinprogress.h \
		keyboard.h \
		testresultdetails.h main.cpp \
		mainwindow.cpp \
		connectivityform.cpp \
		datetimeform.cpp \
		displayforms.cpp \
		homescreen.cpp \
		insertclotchip.cpp \
		openscanclotchip.cpp \
		passcodeunlock.cpp \
		preparepatient.cpp \
		qualityassuranceform.cpp \
		serviceform.cpp \
		setadminpasscode.cpp \
		setpatientid.cpp \
		settingoptionsform.cpp \
		setuserid.cpp \
		setuserpasscode.cpp \
		verifyclotchip.cpp \
		viewtestresultsform.cpp \
		selectnetwork.cpp \
		bluetoothpairing.cpp \
		timelastdose.cpp \
		collectsample.cpp \
		preheatclotchip.cpp \
		testinprogress.cpp \
		keyboard.cpp \
		testresultdetails.cpp
QMAKE_TARGET  = XaTek
DESTDIR       = 
TARGET        = XaTek


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_homescreen.h ui_passcodeunlock.h ui_viewtestresultsform.h ui_settingoptionsform.h ui_setadminpasscode.h ui_serviceform.h ui_qualityassuranceform.h ui_displayforms.h ui_datetimeform.h ui_connectivityform.h ui_setuserid.h ui_setpatientid.h ui_setuserpasscode.h ui_verifyclotchip.h ui_openscanclotchip.h ui_preparepatient.h ui_insertclotchip.h ui_selectnetwork.h ui_bluetoothpairing.h ui_timelastdose.h ui_collectsample.h ui_preheatclotchip.h ui_testinprogress.h ui_keyboard.h ui_testresultdetails.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XaTek.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		XaTek.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5QuickControls2.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Quick.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Qml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile XaTek.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
XaTek.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5QuickControls2.prl:
/usr/lib/x86_64-linux-gnu/libQt5Quick.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Qml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile XaTek.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h connectivityform.h datetimeform.h displayforms.h homescreen.h insertclotchip.h openscanclotchip.h passcodeunlock.h preparepatient.h qualityassuranceform.h serviceform.h setadminpasscode.h setpatientid.h settingoptionsform.h setuserid.h setuserpasscode.h verifyclotchip.h viewtestresultsform.h selectnetwork.h bluetoothpairing.h timelastdose.h collectsample.h preheatclotchip.h testinprogress.h keyboard.h testresultdetails.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp connectivityform.cpp datetimeform.cpp displayforms.cpp homescreen.cpp insertclotchip.cpp openscanclotchip.cpp passcodeunlock.cpp preparepatient.cpp qualityassuranceform.cpp serviceform.cpp setadminpasscode.cpp setpatientid.cpp settingoptionsform.cpp setuserid.cpp setuserpasscode.cpp verifyclotchip.cpp viewtestresultsform.cpp selectnetwork.cpp bluetoothpairing.cpp timelastdose.cpp collectsample.cpp preheatclotchip.cpp testinprogress.cpp keyboard.cpp testresultdetails.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui homescreen.ui passcodeunlock.ui viewtestresultsform.ui settingoptionsform.ui setadminpasscode.ui serviceform.ui qualityassuranceform.ui displayforms.ui datetimeform.ui connectivityform.ui setuserid.ui setpatientid.ui setuserpasscode.ui verifyclotchip.ui openscanclotchip.ui preparepatient.ui insertclotchip.ui selectnetwork.ui bluetoothpairing.ui timelastdose.ui collectsample.ui preheatclotchip.ui testinprogress.ui keyboard.ui testresultdetails.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		Images/XatekUI_StartNewTest.png \
		Images/XatekUI_Battery25.png \
		Images/XatekUI_VerifyingClotChip.png \
		Images/XatekUI_CancelTestInProgress.png \
		Images/XatekUI_Unlock.png \
		Images/XatekUI_CollectSample.png \
		Images/XatekUI_Battery75.png \
		Images/XatekUI_Battery00.png \
		Images/XatekUI_InsertClotChipRCR.gif \
		Images/XatekUI_Brightness.png \
		Images/XatekUI_TestInProgress.png \
		Images/XatekUI_EnterKey.png \
		Images/XatekUI_WiFi.png \
		Images/XatekUI_EnterPatientID.png \
		Images/XatekUI_TimeExpired.png \
		Images/XatekUI_PreparePatient.png \
		Images/XatekUI_Battery50.png \
		Images/XatekUI_EnterUserID.png \
		Images/XatekUI_Battery100.png \
		Images/XatekUI_BatteryCharge.png \
		Images/XatekUI_ViewTestResults.png \
		Images/XatekUI_BackArrow.png \
		Images/XatekUI_TestComplete.png \
		Images/XatekUI_Bluetooth.png \
		Images/XatekUI_OpenScanClotChip.gif \
		Images/XatekUI_Backdrop.png \
		Images/XatekUI_OptionsMenu.png \
		Images/XatekUI_RemoveClotChip.png \
		Images/XatekUI_PreHeatClotChip.png \
		Resources/scripts.js \
		Resources/doseDateTime.qml \
		Resources/dateTimeModule.qml
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_connectivityform.cpp moc_datetimeform.cpp moc_displayforms.cpp moc_homescreen.cpp moc_insertclotchip.cpp moc_openscanclotchip.cpp moc_passcodeunlock.cpp moc_preparepatient.cpp moc_qualityassuranceform.cpp moc_serviceform.cpp moc_setadminpasscode.cpp moc_setpatientid.cpp moc_settingoptionsform.cpp moc_setuserid.cpp moc_setuserpasscode.cpp moc_verifyclotchip.cpp moc_viewtestresultsform.cpp moc_selectnetwork.cpp moc_bluetoothpairing.cpp moc_timelastdose.cpp moc_collectsample.cpp moc_preheatclotchip.cpp moc_testinprogress.cpp moc_keyboard.cpp moc_testresultdetails.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_connectivityform.cpp moc_datetimeform.cpp moc_displayforms.cpp moc_homescreen.cpp moc_insertclotchip.cpp moc_openscanclotchip.cpp moc_passcodeunlock.cpp moc_preparepatient.cpp moc_qualityassuranceform.cpp moc_serviceform.cpp moc_setadminpasscode.cpp moc_setpatientid.cpp moc_settingoptionsform.cpp moc_setuserid.cpp moc_setuserpasscode.cpp moc_verifyclotchip.cpp moc_viewtestresultsform.cpp moc_selectnetwork.cpp moc_bluetoothpairing.cpp moc_timelastdose.cpp moc_collectsample.cpp moc_preheatclotchip.cpp moc_testinprogress.cpp moc_keyboard.cpp moc_testresultdetails.cpp
moc_mainwindow.cpp: passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_connectivityform.cpp: selectnetwork.h \
		keyboard.h \
		bluetoothpairing.h \
		connectivityform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include connectivityform.h -o moc_connectivityform.cpp

moc_datetimeform.cpp: datetimeform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include datetimeform.h -o moc_datetimeform.cpp

moc_displayforms.cpp: displayforms.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include displayforms.h -o moc_displayforms.cpp

moc_homescreen.cpp: openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		homescreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include homescreen.h -o moc_homescreen.cpp

moc_insertclotchip.cpp: setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		insertclotchip.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include insertclotchip.h -o moc_insertclotchip.cpp

moc_openscanclotchip.cpp: insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		openscanclotchip.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include openscanclotchip.h -o moc_openscanclotchip.cpp

moc_passcodeunlock.cpp: homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		passcodeunlock.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include passcodeunlock.h -o moc_passcodeunlock.cpp

moc_preparepatient.cpp: preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		preparepatient.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include preparepatient.h -o moc_preparepatient.cpp

moc_qualityassuranceform.cpp: qualityassuranceform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qualityassuranceform.h -o moc_qualityassuranceform.cpp

moc_serviceform.cpp: serviceform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include serviceform.h -o moc_serviceform.cpp

moc_setadminpasscode.cpp: setadminpasscode.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include setadminpasscode.h -o moc_setadminpasscode.cpp

moc_setpatientid.cpp: keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		setpatientid.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include setpatientid.h -o moc_setpatientid.cpp

moc_settingoptionsform.cpp: setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		keyboard.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		settingoptionsform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include settingoptionsform.h -o moc_settingoptionsform.cpp

moc_setuserid.cpp: setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		setuserid.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include setuserid.h -o moc_setuserid.cpp

moc_setuserpasscode.cpp: setuserpasscode.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include setuserpasscode.h -o moc_setuserpasscode.cpp

moc_verifyclotchip.cpp: testinprogress.h \
		verifyclotchip.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include verifyclotchip.h -o moc_verifyclotchip.cpp

moc_viewtestresultsform.cpp: viewtestresultsform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include viewtestresultsform.h -o moc_viewtestresultsform.cpp

moc_selectnetwork.cpp: keyboard.h \
		selectnetwork.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include selectnetwork.h -o moc_selectnetwork.cpp

moc_bluetoothpairing.cpp: bluetoothpairing.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include bluetoothpairing.h -o moc_bluetoothpairing.cpp

moc_timelastdose.cpp: preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		timelastdose.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include timelastdose.h -o moc_timelastdose.cpp

moc_collectsample.cpp: verifyclotchip.h \
		testinprogress.h \
		collectsample.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include collectsample.h -o moc_collectsample.cpp

moc_preheatclotchip.cpp: collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		preheatclotchip.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include preheatclotchip.h -o moc_preheatclotchip.cpp

moc_testinprogress.cpp: testinprogress.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include testinprogress.h -o moc_testinprogress.cpp

moc_keyboard.cpp: keyboard.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include keyboard.h -o moc_keyboard.cpp

moc_testresultdetails.cpp: testresultdetails.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/david/Qt/Projects/XaTek -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7.4.0 -I/usr/include/x86_64-linux-gnu/c++/7.4.0 -I/usr/include/c++/7.4.0/backward -I/usr/include/clang/6.0.0/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include testresultdetails.h -o moc_testresultdetails.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_homescreen.h ui_passcodeunlock.h ui_viewtestresultsform.h ui_settingoptionsform.h ui_setadminpasscode.h ui_serviceform.h ui_qualityassuranceform.h ui_displayforms.h ui_datetimeform.h ui_connectivityform.h ui_setuserid.h ui_setpatientid.h ui_setuserpasscode.h ui_verifyclotchip.h ui_openscanclotchip.h ui_preparepatient.h ui_insertclotchip.h ui_selectnetwork.h ui_bluetoothpairing.h ui_timelastdose.h ui_collectsample.h ui_preheatclotchip.h ui_testinprogress.h ui_keyboard.h ui_testresultdetails.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_homescreen.h ui_passcodeunlock.h ui_viewtestresultsform.h ui_settingoptionsform.h ui_setadminpasscode.h ui_serviceform.h ui_qualityassuranceform.h ui_displayforms.h ui_datetimeform.h ui_connectivityform.h ui_setuserid.h ui_setpatientid.h ui_setuserpasscode.h ui_verifyclotchip.h ui_openscanclotchip.h ui_preparepatient.h ui_insertclotchip.h ui_selectnetwork.h ui_bluetoothpairing.h ui_timelastdose.h ui_collectsample.h ui_preheatclotchip.h ui_testinprogress.h ui_keyboard.h ui_testresultdetails.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_homescreen.h: homescreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic homescreen.ui -o ui_homescreen.h

ui_passcodeunlock.h: passcodeunlock.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic passcodeunlock.ui -o ui_passcodeunlock.h

ui_viewtestresultsform.h: viewtestresultsform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic viewtestresultsform.ui -o ui_viewtestresultsform.h

ui_settingoptionsform.h: settingoptionsform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic settingoptionsform.ui -o ui_settingoptionsform.h

ui_setadminpasscode.h: setadminpasscode.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic setadminpasscode.ui -o ui_setadminpasscode.h

ui_serviceform.h: serviceform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic serviceform.ui -o ui_serviceform.h

ui_qualityassuranceform.h: qualityassuranceform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic qualityassuranceform.ui -o ui_qualityassuranceform.h

ui_displayforms.h: displayforms.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic displayforms.ui -o ui_displayforms.h

ui_datetimeform.h: datetimeform.ui \
		/usr/lib/qt5/bin/uic \
		/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets/QQuickWidget
	/usr/lib/qt5/bin/uic datetimeform.ui -o ui_datetimeform.h

ui_connectivityform.h: connectivityform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic connectivityform.ui -o ui_connectivityform.h

ui_setuserid.h: setuserid.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic setuserid.ui -o ui_setuserid.h

ui_setpatientid.h: setpatientid.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic setpatientid.ui -o ui_setpatientid.h

ui_setuserpasscode.h: setuserpasscode.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic setuserpasscode.ui -o ui_setuserpasscode.h

ui_verifyclotchip.h: verifyclotchip.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic verifyclotchip.ui -o ui_verifyclotchip.h

ui_openscanclotchip.h: openscanclotchip.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic openscanclotchip.ui -o ui_openscanclotchip.h

ui_preparepatient.h: preparepatient.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic preparepatient.ui -o ui_preparepatient.h

ui_insertclotchip.h: insertclotchip.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic insertclotchip.ui -o ui_insertclotchip.h

ui_selectnetwork.h: selectnetwork.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic selectnetwork.ui -o ui_selectnetwork.h

ui_bluetoothpairing.h: bluetoothpairing.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic bluetoothpairing.ui -o ui_bluetoothpairing.h

ui_timelastdose.h: timelastdose.ui \
		/usr/lib/qt5/bin/uic \
		/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets/QQuickWidget
	/usr/lib/qt5/bin/uic timelastdose.ui -o ui_timelastdose.h

ui_collectsample.h: collectsample.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic collectsample.ui -o ui_collectsample.h

ui_preheatclotchip.h: preheatclotchip.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic preheatclotchip.ui -o ui_preheatclotchip.h

ui_testinprogress.h: testinprogress.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic testinprogress.ui -o ui_testinprogress.h

ui_keyboard.h: keyboard.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic keyboard.ui -o ui_keyboard.h

ui_testresultdetails.h: testresultdetails.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic testresultdetails.ui -o ui_testresultdetails.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

connectivityform.o: connectivityform.cpp connectivityform.h \
		selectnetwork.h \
		keyboard.h \
		bluetoothpairing.h \
		ui_connectivityform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectivityform.o connectivityform.cpp

datetimeform.o: datetimeform.cpp datetimeform.h \
		ui_datetimeform.h \
		mainwindow.h \
		passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datetimeform.o datetimeform.cpp

displayforms.o: displayforms.cpp displayforms.h \
		ui_displayforms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o displayforms.o displayforms.cpp

homescreen.o: homescreen.cpp homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		ui_homescreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homescreen.o homescreen.cpp

insertclotchip.o: insertclotchip.cpp insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_insertclotchip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insertclotchip.o insertclotchip.cpp

openscanclotchip.o: openscanclotchip.cpp openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_openscanclotchip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openscanclotchip.o openscanclotchip.cpp

passcodeunlock.o: passcodeunlock.cpp passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		ui_passcodeunlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passcodeunlock.o passcodeunlock.cpp

preparepatient.o: preparepatient.cpp preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_preparepatient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preparepatient.o preparepatient.cpp

qualityassuranceform.o: qualityassuranceform.cpp qualityassuranceform.h \
		ui_qualityassuranceform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qualityassuranceform.o qualityassuranceform.cpp

serviceform.o: serviceform.cpp serviceform.h \
		ui_serviceform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serviceform.o serviceform.cpp

setadminpasscode.o: setadminpasscode.cpp setadminpasscode.h \
		ui_setadminpasscode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setadminpasscode.o setadminpasscode.cpp

setpatientid.o: setpatientid.cpp setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_setpatientid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setpatientid.o setpatientid.cpp

settingoptionsform.o: settingoptionsform.cpp settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		keyboard.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h \
		ui_settingoptionsform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingoptionsform.o settingoptionsform.cpp

setuserid.o: setuserid.cpp setuserid.h \
		setpatientid.h \
		keyboard.h \
		timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_setuserid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setuserid.o setuserid.cpp

setuserpasscode.o: setuserpasscode.cpp setuserpasscode.h \
		ui_setuserpasscode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setuserpasscode.o setuserpasscode.cpp

verifyclotchip.o: verifyclotchip.cpp verifyclotchip.h \
		testinprogress.h \
		ui_verifyclotchip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o verifyclotchip.o verifyclotchip.cpp

viewtestresultsform.o: viewtestresultsform.cpp viewtestresultsform.h \
		ui_viewtestresultsform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewtestresultsform.o viewtestresultsform.cpp

selectnetwork.o: selectnetwork.cpp selectnetwork.h \
		keyboard.h \
		ui_selectnetwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectnetwork.o selectnetwork.cpp

bluetoothpairing.o: bluetoothpairing.cpp bluetoothpairing.h \
		ui_bluetoothpairing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bluetoothpairing.o bluetoothpairing.cpp

timelastdose.o: timelastdose.cpp timelastdose.h \
		preparepatient.h \
		preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_timelastdose.h \
		mainwindow.h \
		passcodeunlock.h \
		homescreen.h \
		openscanclotchip.h \
		insertclotchip.h \
		setuserid.h \
		setpatientid.h \
		keyboard.h \
		viewtestresultsform.h \
		settingoptionsform.h \
		setadminpasscode.h \
		setuserpasscode.h \
		displayforms.h \
		datetimeform.h \
		connectivityform.h \
		selectnetwork.h \
		bluetoothpairing.h \
		qualityassuranceform.h \
		serviceform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timelastdose.o timelastdose.cpp

collectsample.o: collectsample.cpp collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_collectsample.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collectsample.o collectsample.cpp

preheatclotchip.o: preheatclotchip.cpp preheatclotchip.h \
		collectsample.h \
		verifyclotchip.h \
		testinprogress.h \
		ui_preheatclotchip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preheatclotchip.o preheatclotchip.cpp

testinprogress.o: testinprogress.cpp testinprogress.h \
		ui_testinprogress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testinprogress.o testinprogress.cpp

keyboard.o: keyboard.cpp keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o keyboard.cpp

testresultdetails.o: testresultdetails.cpp testresultdetails.h \
		ui_testresultdetails.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testresultdetails.o testresultdetails.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_connectivityform.o: moc_connectivityform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectivityform.o moc_connectivityform.cpp

moc_datetimeform.o: moc_datetimeform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datetimeform.o moc_datetimeform.cpp

moc_displayforms.o: moc_displayforms.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_displayforms.o moc_displayforms.cpp

moc_homescreen.o: moc_homescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homescreen.o moc_homescreen.cpp

moc_insertclotchip.o: moc_insertclotchip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insertclotchip.o moc_insertclotchip.cpp

moc_openscanclotchip.o: moc_openscanclotchip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openscanclotchip.o moc_openscanclotchip.cpp

moc_passcodeunlock.o: moc_passcodeunlock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passcodeunlock.o moc_passcodeunlock.cpp

moc_preparepatient.o: moc_preparepatient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preparepatient.o moc_preparepatient.cpp

moc_qualityassuranceform.o: moc_qualityassuranceform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qualityassuranceform.o moc_qualityassuranceform.cpp

moc_serviceform.o: moc_serviceform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serviceform.o moc_serviceform.cpp

moc_setadminpasscode.o: moc_setadminpasscode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setadminpasscode.o moc_setadminpasscode.cpp

moc_setpatientid.o: moc_setpatientid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setpatientid.o moc_setpatientid.cpp

moc_settingoptionsform.o: moc_settingoptionsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingoptionsform.o moc_settingoptionsform.cpp

moc_setuserid.o: moc_setuserid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setuserid.o moc_setuserid.cpp

moc_setuserpasscode.o: moc_setuserpasscode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setuserpasscode.o moc_setuserpasscode.cpp

moc_verifyclotchip.o: moc_verifyclotchip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_verifyclotchip.o moc_verifyclotchip.cpp

moc_viewtestresultsform.o: moc_viewtestresultsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewtestresultsform.o moc_viewtestresultsform.cpp

moc_selectnetwork.o: moc_selectnetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectnetwork.o moc_selectnetwork.cpp

moc_bluetoothpairing.o: moc_bluetoothpairing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bluetoothpairing.o moc_bluetoothpairing.cpp

moc_timelastdose.o: moc_timelastdose.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timelastdose.o moc_timelastdose.cpp

moc_collectsample.o: moc_collectsample.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_collectsample.o moc_collectsample.cpp

moc_preheatclotchip.o: moc_preheatclotchip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preheatclotchip.o moc_preheatclotchip.cpp

moc_testinprogress.o: moc_testinprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testinprogress.o moc_testinprogress.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

moc_testresultdetails.o: moc_testresultdetails.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testresultdetails.o moc_testresultdetails.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

